# Generated by Django 5.1.7 on 2025-04-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('posts', models.ManyToManyField(blank=True, related_name='categories', to='posts.posts', verbose_name='Посты')),
            ],
        ),
    ]
