# Generated by Django 5.1.7 on 2025-04-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ('id',), 'verbose_name': 'изображение', 'verbose_name_plural': 'изображения'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ('id',), 'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Название категории')),
                ('posts', models.ManyToManyField(blank=True, related_name='categories', to='posts.posts', verbose_name='Посты')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
