# Generated by Django 5.1.7 on 2025-04-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_images_options_alter_posts_options_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='posts',
        ),
        migrations.AddField(
            model_name='posts',
            name='categories',
            field=models.ManyToManyField(related_name='post_catigoties', to='posts.categories', verbose_name='категории'),
        ),
    ]
